export const extractFormData = form => Array
    .from(form.elements)
    .reduce((acc, { id, value }) => ({ [id]: value, ...acc }), {});

    export const getCurrencySymbol = country => {
        const currencies = {
          gb: "£",
          us: "$",
          au: "$",
          ca: "$",
          in: "₹",
          br: "R$",
          fr: "€",
          de: "€",
          it: "€",
          nl: "€",
          es: "€",
          za: "R",
          jp: "¥",
          cn: "¥",
          ru: "₽",
          mx: "$",
          ar: "$",
          cl: "$",
          co: "$",
          pe: "S/",
          kr: "₩",
          se: "kr",
          no: "kr",
          dk: "kr",
          ch: "CHF",
          at: "€",
          be: "€",
          gr: "€",
          hu: "Ft",
          pl: "zł",
          cz: "Kč",
          sk: "€",
          pt: "€",
          fi: "€",
          ie: "€",
          sg: "S$",
          my: "RM",
          th: "฿",
          id: "Rp",
          ph: "₱",
          vn: "₫",
          tr: "₺",
          eg: "EGP",
          sa: "ر.س",
          ae: "د.إ",
          qa: "ر.ق",
          kw: "د.ك",
          om: "ر.ع.",
          bh: "د.ب",
          jo: "د.ا",
          lb: "ل.ل",
          sy: "£S",
          iq: "ع.د",
          ir: "﷼",
          pk: "₨",
          bd: "৳",
          lk: "රු",
          np: "₨",
          mm: "Ks",
          kh: "៛",
          la: "₭",
          vn: "₫",
          tl: "$",
          au: "$",
          nz: "$",
          fj: "$",
          pg: "K",
          sb: "SI$",
          vu: "VT",
          fm: "$",
          mh: "$",
          ki: "$",
          to: "T$",
          ws: "WS$",
          tv: "TV$",
          nr: "A$",
        };
        return currencies[country] || "";
      };
      
      